CREATE TABLE animals(id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,name VARCHAR(255),date_of_birth DATE,escape_attempts INT,neutered BOOLEAN,weight_kg DECIMAL);
ALTER TABLE animals
ADD COLUMN species VARCHAR(255);