CREATE TABLE animals(id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,name VARCHAR(255),date_of_birth DATE,escape_attempts INT,neutered BOOLEAN,weight_kg DECIMAL);
ALTER TABLE animals
ADD COLUMN species VARCHAR(255);

CREATE TABLE owners(id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,full_name VARCHAR(255) ,age INT);
CREATE TABLE species(id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,name VARCHAR(255));
ALTER TABLE animals
DROP COLUMN species;

ALTER TABLE animals
ADD COLUMN species_id INT;
ADD CONSTRAINT fk_species
FOREIGN KEY(species_id)
REFERENCES species(id)
ON DELETE CASCADE;

ALTER TABLE animals
ADD COLUMN owner_id INT;
ADD CONSTRAINT fk_owners
FOREIGN KEY(owner_id)
REFERENCES owners(id)
ON DELETE CASCADE;